# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_remove_matcher_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='revision',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
