# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_remove_project_specific_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugscache',
            name='whiteboard',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugscache',
            name='modified',
            field=models.DateTimeField(db_index=True),
        ),
    ]
