# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 01:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0011_inc_extra_options_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='performancedatum',
            managers=[
                ('performance', django.db.models.manager.Manager()),
            ],
        ),
    ]
